### ISSUE TITLE
Add tmpfs lab instruction

### ISSUE THREAD

**Issue by vityaman** [secs-dev/os-course#1]
## Описание

Хочется, чтобы лаба `networkfs` стала лабой на разработку `tmpfs`, данные которой располагались бы в оперативной памяти. В таком виде она будет на 10 баллов. Со звездочкой можно также сделать так, чтобы файлы хранились на удаленном сервере. Протокол общения с сервером не зафиксирован. Каждый пишет такой сервер, какой ему хочется. Сервер можно писать на любом ЯП. Это будет давать +5 баллов.

Таким образом, хочется вырезать упоминания netfs из лабы и вести ее, будто мы делаем tmpfs, а в конце добавить задание со звездочкой.

## Полезные ссылки

Original statement: https://github.com/vityaman-edu/os-networkfs/blob/8-module-linufs-web-rw/doc/statement.pdf

**Comment by e1turin** [comment]
Prepared
